### ISSUE TITLE
sendkeys not working on IE 11

### ISSUE THREAD

**Issue by Prudwi** [SeleniumHQ/www.seleniumhq.org#127]
Am trying send keys into a text area, it says that send keys was successful in the logs. But, it is not actually sending the keys to that text area. Below is the Text area HTML info:

"<textarea name="sr_essm_info_survey_comments_2" maxlength="500" rows="10" cols="50" onfocus="this.select()">automation</textarea>"

Ran the selenium script on Selenium 2.53.1, internet explorer 11.576 and Windows.

Please help me with this issue.

**Comment by lmtierney** [comment]
This is the repo for the seleniumhq.org website, not the webdriver repo. Also, this is a question rather than an issue. Please read [Bug Reporting](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#bug-reports) and either raise an issue with a reproducible test case or seek help from the mailing list
