### ISSUE TITLE
font problem on web site

### ISSUE THREAD

**Issue by lmtierney** [SeleniumHQ/www.seleniumhq.org#144]
_From @dofinium on May 19, 2017 8:51_

There are some problem with some symbols, please look at the attached image. 

![seleniumsite](https://cloud.githubusercontent.com/assets/8024202/26240298/ce2f69de-3c80-11e7-927d-7d8b2345deb7.png)

_Copied from original issue: SeleniumHQ/selenium#4045_

**Comment by lmtierney** [comment]
@tourdedave

**Comment by tourdedave** [comment]
Hmm, strange. It looks like HTML codes aren't be translated correctly.

**Comment by tourdedave** [comment]
And I can't replicate it locally. Hmm.

**Comment by tourdedave** [comment]
@lukeis

**Comment by lukeis** [comment]
why'd ya'll break it!

probably google app engine upgraded something on us and we'll need to update our dependencies...

**Comment by jfisher446** [comment]
I'm seeing the pictured output across all browsers (iOS Safari, Win10: Edge, Chrome, IE). I also cannot replicate when I run the server locally, however...
It appears to be an encoding issue where the three bytes that make up the curly quote characters are being rendered as separately as 3 1-byte characters instead of as a 3-byte character. 
When opening the affected docs locally, I see that the src file contains actual curly quotes. When I render locally as UTF-8, I see them. When converted to Windows 1252, however, they render like they are in my browser and in the OP's screenshot. 
I'm not familiar with this tech stack, but examining the config and the DOM of the live website appears that UTF-8 is being specified....so I'm not sure how to fix. 
Would it be wrong to work up a PR to convert all curly quotes to straight quotes? Is the typography all that important?

**Comment by luiscardozo** [comment]
This seems to be a problem with the codification (charset). Newer browsers does not have anymore the option to change the charset (they auto-detect it).

Viewing with Chrome 49 (on a VirtualBox), I see that it detects the page as Win-1256 (even thought in the 
html it is set as charset=utf-8). When selecting UTF-8 as charset in Chrome, it shows the characters well.

![00charset](https://user-images.githubusercontent.com/763637/27333926-939f6796-5595-11e7-9ece-83c2c244cfd9.png)


Seems to be a missconfiguration on the web server. In the response header, I see that it says "charset=iso-8859-1"

![00headers](https://user-images.githubusercontent.com/763637/27333977-bebdf492-5595-11e7-8b41-e8a2c7aa10e9.png)

**Comment by shs96c** [comment]
I believe that 8a75a5a91d938e5af4f7e943fcfb8ab56506d07d fixes this problem.
