### ISSUE TITLE
Does anyone know how to handle Chrome Basic Authentication in Selenium Java?

### ISSUE THREAD

**Issue by kaukul** [SeleniumHQ/www.seleniumhq.org#162]
Does anyone know how to handle Chrome Basic Authentication in Selenium Java?
It does not get identified as an Alert so Alert object does not work.. :(

**Comment by lukeis** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users)

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect.

See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
