### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by Weiweim** [SeleniumHQ/www.seleniumhq.org#180]
In the page,
 http://www.seleniumhq.org/docs/04_webdriver_advanced.jsp#explicit-and-implicit-waits-reference
Expected Conditions
There are some common conditions that are frequently encountered when automating web browsers. Listed below are a few examples for the usage of such conditions. The Java, C#, and Python bindings include convienence methods so you don’t have to code an ExpectedCondition class yourself or create your own utility package for them.
The word [convienence] spelling error, should be [convenience]

**Comment by einsteinsfool** [comment]
Shouldn't it be an adjective altogether?
So it would be:

> The Java, C#, and Python bindings include **convenient** methods so you don’t have to code an ExpectedCondition class yourself or create your own utility package for them.

**Comment by mmerrell** [comment]
"Convenience methods" is a pretty well-accepted term for "helper methods", where the caller can just call the method with minimal effort in order to set the environment to how they want it. There's a pretty good description here: http://wiki.c2.com/?ConvenienceMethods.

I believe this is a better term to use than merely calling the methods "convenient", because, while awkward in a traditional English sense, this term has been adopted within the industry as having its own semantics, separate from simply saying "convenient".

That said, it looks like the spelling should be fixed. I've submitted a PR.

**Comment by jimevans** [comment]
@mmerrell Can you amend your PR to remove C# from the list of languages that include ExpectedConditions? They’ve been deprecated in the .NET language binding, and will eventually be removed.

**Comment by mmerrell** [comment]
Sure. I’m trying to go through all the issues that can be done really quick, so if you have any more suggestions/requests, I’ll work to make them happy. I’ll amend the PR when I get to a computer. 
MM

**Comment by lukeis** [comment]
fixed with #198
