### ISSUE TITLE
Comments make test fail if not included with script, Close window doesn't work/ removed?

### ISSUE THREAD

**Issue by modnar1226** [SeleniumHQ/www.seleniumhq.org#201]
using comments with out test script cause failure to test. As well as blank commands. this was not the case in the last release. Also the close window command seems to be missing from the command list. i have tests written using the last release. Now the command does not close the window but doesn't fail the test, just kinda glosses over the command.  

Edit: upon further study the close element does work its the click at command. a single command for click at (button that opens link) opens two pages instead of one.

**Comment by lukeis** [comment]
for selenium issues, please log bugs against the selenium project - https://github.com/SeleniumHQ/selenium

Be sure to include complete steps to reproduce so that someone can look further into your issue. You have not provided that information thus far.

This is the documentation website repository and only issues with the documentation site should be reported here.
