### ISSUE TITLE
staleElementReference error on action class

### ISSUE THREAD

**Issue by ishah09** [SeleniumHQ/www.seleniumhq.org#207]
As we use action class for usually Click event. Somehow I am getting exception on each action class usage. It throws StaleElementReference exception on every action method, Not working for single instance.

Element does not able to click while Debugging also. When I replaced it by simple Click() method, It worked fine. But, I can't use click method based on some other exception dependency.

What could went wrong,

using OpenQA.Selenium.Interactions;

Actions action = new Actions(driver);
action.MoveToElement(WebElement).Click().Perform();

Selenium version : 3.14
Selenium Chrome WebDriver : 2.43

**Comment by lmtierney** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users).

For issues please provide a [concise reproducible test case](http://sscce.org/) and describe what results you are seeing and what results you expect. See [CONTRIBUTING.md](https://github.com/SeleniumHQ/selenium/blob/master/CONTRIBUTING.md#issue-contributions)
