### ISSUE TITLE
Inside section Tag of html 5, can't click any element using Selenium webDriver

### ISSUE THREAD

**Issue by msayem63** [SeleniumHQ/www.seleniumhq.org#226]
If use WebDriver Click method, Actions Class, or JavascriptExecutor, result shows 
org.openqa.selenium.ElementClickInterceptedException: element click intercepted: Element

Is Selenium unable to control element inside Section Tag?

**Comment by diemol** [comment]
This is a question rather than an issue. Please send questions to the [selenium user group](https://groups.google.com/forum/#!forum/selenium-users), to [StackOverflow](https://stackoverflow.com/questions/tagged/selenium), or join us in the [IRC/Slack channel](https://goo.gl/9o4J3Y) where the community can help you as well.
